# ===================================================================
#           CRAFT - Quick Start Configuration (v1.0)
# ===================================================================
# This file is for the most common use case.
# For advanced options (e.g., pre-split data, CV), see config_full.yaml.

# --- 1. Experiment Basics (EDIT THESE) ---
experiment_name: "ET30"
task_type: "regression"  # "regression", "binary_classification", or "multiclass_classification"

# --- 2. Data Source (EDIT THESE) ---
# Assumes you have a single CSV file.
data:
  source_mode: "single_file"  # This is fixed for the simple config
  single_file_config:
    main_file_path: "data/ET30_standardized_cleaned.csv"  # <-- Path to your data file
    smiles_col: "Standardized_SMILES"                      # <-- Name of the SMILES column
    target_col: "ET30"                          # <-- Name of the target property column
    precomputed_features:
      feature_columns: null   # Keep as null unless you have pre-calculated features in the file

# --- 3. Models to Run (EDIT THIS) ---
# Available: xgb, lgbm, rf, cat, hgb, dt, knn, svr, ridge, ann, adab, lr, svc, krr
training:
  models_to_run:
    - "cat"
    # - "rf"
    # - "lgbm"

  
  # Number of HPO trials per model. 50 is a good start.
  n_trials: 100
  quiet_optuna: true


# --- 4. Standard Settings (Usually no need to change for a first run) ---
# Default features: Morgan fingerprints (1024 bits) and RDKit 2D descriptors.
features:
  generators:
    # - type: "morgan"
    #   nBits: 1024
    #   radius: 2
    - type: "maccs"
    - type: "rdkit_descriptors"
    # - type: "unimol"
    #   model_version: "v2"
    #   model_size: "84m"


  scaling: true  # Applies StandardScaler to features

# Default splitting: 80% train, 10% validation, 10% test.
split_mode: "train_valid_test"  # This is fixed for the simple config
split_config:
  train_valid_test:
    train_size: 0.8
    valid_size: 0.1
    test_size: 0.1
    random_state: 42
  # The cross_validation block is omitted for simplicity.


