# ===================================================================
#           CRAFT - Advanced Feature & CV Configuration (v1.2)
# ===================================================================
# This file demonstrates per-column features with 5-fold cross-validation.

# --- 1. Experiment Basics ---
experiment_name: "S17"  # <-- 建议填写
task_type: "regression"

# --- 2. Data Source ---
data:
  source_mode: "single_file"
  single_file_config:
    main_file_path: "data/reactions_with_features.csv"
    
    smiles_col: 
      - "Reactant1"
      - "Reactant2"
      - "Ligand"
      
    target_col: "ee"
    
    # Precomputed features from the 5th column to the end
    precomputed_features:
      feature_columns: "4:39" 

# --- 3. Models to Run ---
training:
  models_to_run:
    - "svr"
    - "cat"
    - "lgbm"
    - "rf"
    - "xgb"
    - "hgb"
    - "knn"
    - "krr"
    - "dt"
    - "ridge"
    - "adab"
  n_trials: 100
  quiet_optuna: true

# --- 4. Feature Generation (Per-Column Mode) ---
# CORRECTED: Keys now match the names in `smiles_col`
features:
  per_smiles_col_generators:
    
    # Features for the "Reactant1" column
    Reactant1:
      - type: "maccs"
        
    # Features for the "Reactant2" column
    Reactant2:
      - type: "maccs"
      
    # Features for the "Ligand" column
    Ligand:
      - type: "maccs"
      # - type: "unimol"
      #   model_version: "v2"
      #   model_size: "84m"

  scaling: true

# --- 5. Splitting (MODIFIED for 5-Fold Cross-Validation) ---
# The data will be split into an 80% training set and a 20% final test set.
# The 80% training set will then be used for 5-fold CV during HPO.
# split_mode: "cross_validation"
# split_config:
#   cross_validation:
#     n_splits: 5               # <-- Number of CV folds
#     test_size_for_cv: 0.05     # <-- Size of the hold-out test set
#     random_state: 42

split_mode: "train_valid_test"  # This is fixed for the simple config
split_config:
  train_valid_test:
    train_size: 0.9
    valid_size: 0.05
    test_size: 0.05
    random_state: 42