name: chemia
channels:
  - conda-forge
  - pytorch
  - pyg
  - defaults

dependencies:
  # Python - Specify version range
  - python>=3.8,<3.13

  # Core scientific computing - Add reasonable upper bounds
  - numpy>=1.21.0,<2.0
  - pandas>=1.3.0,<3.0
  - scipy>=1.7.0,<2.0

  # Machine learning core
  - scikit-learn>=1.0.2,<2.0

  # Add missing system dependencies
  - typing_extensions>=4.0.0
  - packaging>=21.0

  # PyTorch ecosystem - Recommend installing complete suite
  # Note: Please choose appropriate version for your system
  # GPU version (recommended):
  # conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
  # CPU version:
  # conda install pytorch torchvision torchaudio cpuonly -c pytorch
  
  # If PyTorch is already installed, you can enable the following lines:
  # - pytorch>=1.11.0,<3.0
  # - torchvision>=0.12.0
  # - torchaudio>=0.11.0

  # Graph Neural Networks (if needed)
  # conda install pyg -c pyg
  # - pytorch-geometric

  # Chemical informatics
  - rdkit>=2022.03.1

  # Data processing
  - pyyaml>=6.0,<7.0
  - joblib>=1.1.0,<2.0
  - tqdm>=4.62.0,<5.0

  # Visualization - Complete installation
  - matplotlib>=3.5.0,<4.0
  - seaborn>=0.11.0,<1.0

  # Development tools (optional)
  - jupyter>=1.0.0
  - jupyterlab>=3.0.0,<5.0

  # Pip dependencies
  - pip>=21.0
  - pip:
    # Machine Learning - Gradient Boosting (add version upper bounds)
    - xgboost>=1.6.0,<4.0
    - lightgbm>=3.3.0,<5.0
    - catboost>=1.0.4,<2.0
    
    # Hyperparameter optimization
    - optuna>=3.0.0,<5.0
    
    # Enhanced UI
    - rich>=12.0.0,<14.0
    
    # Additional visualization
    - plotly>=5.0.0,<6.0
    
    # Development tools (optional)
    - pytest>=7.0.0,<9.0
    - pytest-cov>=3.0.0,<5.0
    - flake8>=4.0.0,<8.0
    - black>=22.0.0,<25.0

# Environment variables
variables:
  # Set reasonable thread count
  OMP_NUM_THREADS: "4"
  MKL_NUM_THREADS: "4"
  
# Post-installation scripts (optional)
# post_install:
#   - echo "CHEMIA environment setup complete!"
#   - echo "Remember to install PyTorch manually for your system" 