# Advanced Graph Construction Features Configuration
# This example demonstrates the enhanced graph building capabilities for multiple SMILES processing

metadata:
  name: "Advanced Graph Features Demo"
  description: "Showcases feature concatenation, reaction graphs, and custom fusion"
  version: "1.0"
  created_by: "CRAFT Framework"
  tags: ["advanced", "graph-neural-networks", "multi-smiles", "features"]

# Data Configuration
data:
  file_path: "data/reaction_dataset.csv"
  target_column: "yield"
  smiles_columns: ["catalyst_smiles", "reactant_1_smiles", "reactant_2_smiles", "product_smiles"]
  task_type: "regression"  # or "classification"
  
  # Advanced SMILES Configuration
  molecule_roles:
    catalyst_smiles: "catalyst"
    reactant_1_smiles: "reactant" 
    reactant_2_smiles: "reactant"
    product_smiles: "product"
  
  # Custom feature columns for fusion
  custom_feature_columns:
    - "temperature"
    - "pressure" 
    - "reaction_time"
    - "solvent_polarity"
    - "catalyst_loading"

# Data Preprocessing
preprocessing:
  # Standard preprocessing
  remove_duplicates: true
  handle_missing: "drop"
  
  # Custom feature processing
  normalize_custom_features: true
  custom_feature_scaling: "standard"  # options: "standard", "minmax", "robust"
  
  # Graph preprocessing
  max_atoms_per_molecule: 150
  add_self_loops: true

# Data Splitting
split:
  method: "random"
  test_size: 0.2
  validation_size: 0.2
  random_state: 42
  stratify: false

# Training Configuration - Multiple Graph Construction Modes
training:
  # GNN models supporting advanced graph features
  models_to_run: ["gcn", "gat", "mpnn", "ensemble_gnn"]
  n_trials: 20  # Hyperparameter optimization trials per model
  
  # Training parameters
  max_epochs: 150
  early_stopping_patience: 25
  batch_size: 64
  
  # Cross-validation
  cv_folds: 5

# Feature Engineering (Traditional features for comparison)
features:
  enabled: true
  molecular_descriptors:
    - "morgan_fingerprints"  # For comparison with GNN features
  
  descriptor_config:
    morgan_fingerprints:
      radius: 2
      # Note: no nBits for Morgan as we'll use variable length

# Advanced Graph Construction Configurations
graph_construction:
  
  # Mode 1: Traditional Batch Mode (baseline)
  batch_mode:
    enabled: true
    mode: "batch"
    description: "Traditional approach - separate molecular graphs batched together"
  
  # Mode 2: Feature-Level Concatenation
  feature_concat_mode:
    enabled: true
    mode: "feature_concat"
    description: "Concatenate molecular-level features from all SMILES"
    molecular_feature_size: 50  # Standardized molecular descriptor vector size
    
  # Mode 3: Reaction Graph Construction
  reaction_graph_mode:
    enabled: true
    mode: "reaction_graph"
    description: "Unified reaction graph with virtual reaction center"
    
    # Reaction graph parameters
    add_reaction_center: true
    reaction_center_connections: "all_molecules"  # Connect center to all molecules
    edge_type_encoding: true  # Use different edge types for different relationships
    
    # Virtual node features
    reaction_center_features: "averaged"  # How to compute reaction center features
    
  # Mode 4: Custom Feature Fusion
  custom_fusion_mode:
    enabled: true
    mode: "custom_fusion"
    description: "Fuse graph embeddings with custom experimental features"
    
    # Fusion configuration
    fusion_method: "attention"  # options: "concatenate", "attention", "gated", "transformer"
    custom_feature_dim: 5  # Dimension of custom features (temperature, pressure, etc.)
    graph_embed_dim: 128   # Graph embedding dimension
    output_dim: 256        # Final fused representation dimension
    
    # Custom features to include
    include_conditions: true    # Reaction conditions (T, P, time)
    include_concentrations: true  # Reactant concentrations if available
    include_catalyst_loading: true

# Model-Specific Configurations for Advanced Features
model_configs:
  
  # GCN with different graph construction modes
  gcn:
    base_params:
      hidden_dim: [64, 128, 256]
      num_layers: [3, 4, 5]
      dropout_rate: [0.1, 0.2, 0.3]
    
    # Mode-specific adaptations
    advanced_features:
      supports_all_modes: true
      feature_concat_hidden: [128, 256]  # Hidden dims for feature concat mode
      fusion_attention_heads: [4, 8]     # Attention heads for custom fusion
  
  # GAT with advanced attention mechanisms
  gat:
    base_params:
      hidden_dim: [64, 128, 256]
      num_layers: [3, 4, 5] 
      num_heads: [4, 8, 12]
      attention_dropout: [0.1, 0.2]
    
    advanced_features:
      supports_all_modes: true
      reaction_graph_attention: true     # Use attention for reaction center connections
      fusion_cross_attention: true      # Cross-attention for custom feature fusion
  
  # MPNN for reaction graph processing
  mpnn:
    base_params:
      hidden_dim: [64, 128, 256]
      num_layers: [3, 4, 5]
      message_hidden_dim: [64, 128]
      num_message_steps: [3, 4, 5]
    
    advanced_features:
      supports_modes: ["batch", "reaction_graph", "custom_fusion"]
      reaction_message_passing: true    # Specialized message passing for reaction graphs
      edge_type_aware: true            # Use edge types in message passing
  
  # Ensemble GNN combining multiple architectures
  ensemble_gnn:
    base_params:
      models: [["gcn", "gat"], ["gcn", "mpnn"], ["gat", "mpnn"]]
      ensemble_method: ["weighted_average", "attention", "stacking"]
    
    advanced_features:
      supports_all_modes: true
      mode_specific_ensembles: true     # Different ensembles for different modes
      cross_mode_fusion: true          # Ensemble predictions from different graph modes

# Evaluation Configuration
evaluation:
  metrics:
    regression: ["r2", "rmse", "mae", "mape"]
    classification: ["accuracy", "f1", "precision", "recall", "auc"]
  
  # Advanced evaluation
  analyze_graph_modes: true           # Compare performance across graph construction modes
  feature_importance: true            # Analyze importance of custom features in fusion
  ablation_study:
    enabled: true
    test_without_custom_features: true  # Test GNN performance without custom features
    test_traditional_vs_gnn: true      # Compare with traditional ML on molecular features

# Optimization Configuration
optimization:
  enabled: false  # This config is for training only
  
# Advanced Analysis and Visualization
analysis:
  enabled: true
  
  # Graph analysis
  visualize_graphs: true
  compare_graph_modes: true
  analyze_reaction_centers: true      # For reaction graph mode
  
  # Feature analysis
  custom_feature_correlation: true
  graph_vs_traditional_features: true
  
  # Model interpretation
  attention_visualization: true       # For GAT models
  graph_explainability: true
  fusion_analysis: true              # Analyze how custom features influence predictions

# Output Configuration  
output:
  base_directory: "results"
  save_models: true
  save_predictions: true
  save_visualizations: true
  
  # Advanced outputs
  save_graph_representations: true   # Save computed graph embeddings
  save_attention_weights: true       # For attention-based models
  save_fusion_weights: true          # For custom fusion models
  
  # Detailed logs
  log_graph_construction_stats: true
  log_fusion_performance: true
  log_ablation_results: true

# Computational Configuration
compute:
  device: "auto"  # "cuda", "cpu", or "auto"
  num_workers: 4
  pin_memory: true
  
  # Memory management for large graphs
  gradient_accumulation_steps: 1
  max_memory_usage: "8GB"
  enable_mixed_precision: true

# Experimental Features (Advanced Users)
experimental:
  enabled: false
  
  # Graph augmentation
  graph_augmentation: false
  augmentation_methods: ["node_dropout", "edge_dropout", "feature_noise"]
  
  # Dynamic graph construction
  dynamic_graph_modes: false         # Switch between modes during training
  adaptive_fusion: false             # Learn optimal fusion strategy
  
  # Meta-learning for graph construction
  learn_graph_construction: false    # Learn optimal graph construction for each sample 