task_type: "regression"

data:
  source_mode: "single_file"
  single_file_config:
    main_file_path: "data/reactions_with_features.csv"
    smiles_col: ["Reactant1", "Reactant2", "Ligand"]
    target_col: "ee"  # The target column to predict
    precomputed_features:
      feature_columns: "5:"  # Include Temp column as feature (from column 5)

training:
  models_to_run: ["histgradientboosting"]  # Only test HistGradientBoosting
  n_trials: 3  # Small number for quick test
  quiet_optuna: true

features:
  per_smiles_col_generators:
    Reactant1: 
      - type: "maccs"  # MACCS keys (fixed 166 bits)
    Reactant2: 
      - type: "maccs"  # MACCS keys (fixed 166 bits)
    Ligand: 
      - type: "rdkit_descriptors"
  scaling: true

split_mode: "cross_validation"
split_config:
  cross_validation:
    n_splits: 5
    test_size_for_cv: 0.1
    random_state: 42
    shuffle: true 