task_type: "regression"

data:
  source_mode: "single_file"
  single_file_config:
    main_file_path: "data/reactions_with_features.csv"
    smiles_col: ["Reactant1", "Reactant2"]
    target_col: "ee"
    feature_cols: ["Temp"]

# Split configuration
split_config:
  strategy: "random"
  test_ratio: 0.15
  val_ratio: 0.15
  random_seed: 42

# Feature configuration for GNN models
features:
  include_temperature: true
  # GNN models work directly with molecular graphs
  # No traditional fingerprints needed - they learn representations from graph structure
  molecular:
    reactant1:
      smiles_column: "Reactant1"
      # GNNs use graph structure directly, no descriptors needed
    reactant2:
      smiles_column: "Reactant2"
      # GNNs use graph structure directly, no descriptors needed

# Training configuration with focus on GNN models
training:
  models_to_run: ["gcn", "gat", "mpnn", "afp", "gtn", "ensemble_gnn"]
  n_trials: 5  # Small number for quick testing
  cv_folds: 3

# Output directory
output_dir: "output/gnn_demo/"

# Advanced settings for GNN training
gnn_settings:
  max_epochs: 50
  early_stopping_patience: 10
  batch_size: 32
  device: "auto"  # Use GPU if available, otherwise CPU

# Alternative: Traditional ML models for comparison
# Uncomment to compare with traditional approaches
# training:
#   models_to_run: ["xgboost", "randomforest", "gcn", "gat"]
#   n_trials: 10
#   cv_folds: 5 