# ===================================================================
#           CRAFT - Quick Start Configuration (v1.0)
# ===================================================================
# This file is for the most common use case.
# For advanced options (e.g., pre-split data, CV), see config_full.yaml.

# --- 1. Experiment Basics (EDIT THESE) ---
experiment_name: "Simple_Demo"
task_type: "regression"  # "regression", "binary_classification", or "multiclass_classification"

# --- 2. Data Source (EDIT THESE) ---
# Assumes you have a single CSV file.
data:
  source_mode: "single_file"  # This is fixed for the simple config
  single_file_config:
    main_file_path: "data/reactions.csv"  # <-- Path to your data file
    smiles_col: ["Catalyst", "Reactant1", "Reactant2"]    # <-- Names of the SMILES columns
    target_col: "yield"                         # <-- Name of the target property column
    precomputed_features:
      feature_columns: null   # Keep as null unless you have pre-calculated features in the file

# --- 3. Models to Run (EDIT THIS) ---
# Available algorithms (18 total):
# 
# Gradient Boosting: xgb, lgbm, catboost, gbdt, histgradientboosting
# Tree Ensembles: rf, extratrees, adaboost
# Linear Regularized: ridge, elasticnet, lasso, bayesianridge
# Advanced/Kernel: gpr, krr, svr
# Neural Networks: ann
# Simple Methods: kneighbors, sgd
training:
  models_to_run:
    # Select best algorithms for small-medium datasets
    - "gpr"           # Gaussian Process (excellent for small datasets)
    - "krr"           # Kernel Ridge Regression
    - "bayesianridge" # Bayesian Ridge (strong regularization)
    # - "xgb"         # XGBoost
    # - "lgbm"        # LightGBM  
    # - "rf"          # Random Forest
    # - "ann"         # Neural Network

  
  # Number of HPO trials per model. 20 is reasonable for quick runs.
  n_trials: 20
  quiet_optuna: true


# --- 4. Standard Settings (Usually no need to change for a first run) ---
# Default features: MACCS keys and RDKit 2D descriptors.
features:
  per_smiles_col_generators:
    Catalyst:
      - type: "maccs"  # MACCS keys (fixed 166 bits)
      - type: "rdkit_descriptors"
    Reactant1:
      - type: "maccs"  # MACCS keys (fixed 166 bits)
    Reactant2:
      - type: "maccs"  # MACCS keys (fixed 166 bits)

  scaling: true  # Applies StandardScaler to features

# Default splitting: 80% train, 10% validation, 10% test.
split_mode: "train_valid_test"  # This is fixed for the simple config
split_config:
  train_valid_test:
    train_size: 0.8
    valid_size: 0.1
    test_size: 0.1
    random_state: 42
  # The cross_validation block is omitted for simplicity.


