# Reaction Graph Construction Mode Configuration
# This mode creates a unified reaction graph with a virtual reaction center node

metadata:
  name: "Reaction Graph Mode Demo"
  description: "Build unified reaction graphs with virtual reaction center"
  use_case: "For modeling chemical reactions as unified graph structures"

# Data Configuration
data:
  file_path: "data/catalytic_reactions.csv" 
  target_column: "conversion_rate"
  smiles_columns: ["catalyst_smiles", "substrate_smiles", "product_smiles", "solvent_smiles"]
  task_type: "regression"
  
  # Define molecular roles for reaction graph construction
  molecule_roles:
    catalyst_smiles: "catalyst"
    substrate_smiles: "reactant"
    product_smiles: "product" 
    solvent_smiles: "solvent"

# Data Splitting
split:
  method: "random"
  test_size: 0.2
  validation_size: 0.2 
  random_state: 42

# Training Configuration - Reaction Graph Mode
training:
  models_to_run: ["gcn", "gat", "mpnn"]  # Models that work well with reaction graphs
  n_trials: 20
  max_epochs: 150
  early_stopping_patience: 25
  batch_size: 16  # Smaller batches for larger graphs
  cv_folds: 5

# Graph Construction - Reaction Graph Mode  
graph_construction:
  mode: "reaction_graph"
  
  # Reaction center configuration
  add_reaction_center: true
  reaction_center_features: "averaged"  # Average features from all molecules
  
  # Connection strategy
  reaction_center_connections: "all_molecules"  # Connect center to all molecules
  
  # Edge type encoding
  edge_type_encoding: true
  edge_types:
    molecular_bond: 0        # Normal chemical bonds within molecules
    reaction_participates: 1 # Reactant/product to reaction center
    catalyzes: 2            # Catalyst to reaction center  
    solvent_interaction: 3  # Solvent to reaction center
  
  # This mode will:
  # 1. Convert each SMILES to individual molecular graphs
  # 2. Create a virtual "reaction center" node
  # 3. Connect all molecules to the reaction center with typed edges
  # 4. Result: Single unified reaction graph with N_atoms + 1 nodes

# Model Configuration for Reaction Graphs
model_configs:
  gcn:
    hidden_dim: [128, 256]
    num_layers: [3, 4, 5]  # More layers to propagate info through reaction center
    dropout_rate: [0.1, 0.2, 0.3]
    # GCN will use edge types in message passing
  
  gat:
    hidden_dim: [128, 256] 
    num_layers: [3, 4, 5]
    num_heads: [4, 8, 12]
    attention_dropout: [0.1, 0.2]
    # GAT can learn different attention patterns for different edge types
  
  mpnn:
    hidden_dim: [128, 256]
    num_layers: [3, 4, 5]
    message_hidden_dim: [64, 128]
    num_message_steps: [3, 4, 5]
    # MPNN can use different message functions for different edge types
    edge_type_aware: true  # Enable edge-type-aware message passing

# Evaluation
evaluation:
  metrics:
    regression: ["r2", "rmse", "mae"]
  
  # Reaction-specific analysis
  analyze_reaction_center: true  # Analyze learned reaction center representations
  visualize_reaction_graphs: true  # Visualize some example reaction graphs

# Output
output:
  base_directory: "results/reaction_graph_mode"
  save_models: true
  save_predictions: true
  save_reaction_graphs: true  # Save example reaction graph visualizations
  
# Advantages of Reaction Graph Mode:
# ✓ Models the entire reaction as a unified system
# ✓ Captures inter-molecular interactions through reaction center
# ✓ Can learn reaction-specific patterns
# ✓ Naturally handles variable numbers of reactants/products
# ✓ Edge types enable different interaction modeling
#
# Disadvantages: 
# ✗ Larger graphs (slower training)
# ✗ More complex architecture
# ✗ Requires good molecular role annotation
# ✗ May overfit on small datasets

# Technical Details:
# Graph Structure:
# - Nodes: All atoms from all molecules + 1 reaction center node
# - Edges: 
#   * Intra-molecular bonds (type 0)
#   * Reactant atoms ↔ reaction center (type 1) 
#   * Catalyst atoms ↔ reaction center (type 2)
#   * Solvent atoms ↔ reaction center (type 3)
#   * Product atoms ↔ reaction center (type 1)
#
# Information Flow:
# 1. Atoms exchange information within molecules (normal bonds)
# 2. Information flows from all molecules to reaction center
# 3. Reaction center aggregates and redistributes information
# 4. Final prediction based on reaction center representation 