# ===================================================================
#                Chemia - Simple Regression Training
# ===================================================================
# A straightforward configuration for regression model training
# with commonly used algorithms and minimal setup.
# ===================================================================

experiment_name: "Simple_Regression_Training"
task_type: "regression"

# --- Data Configuration ---
data:
  source_mode: "single_file"
  single_file_config:
    main_file_path: "data/reactions.csv"
    smiles_col: ["Catalyst", "Reactant1", "Reactant2"]
    target_col: "yield"  # Target column to predict
    precomputed_features:
      feature_columns: null  # No precomputed features

# --- Training Configuration ---
training:
  # Select popular and reliable algorithms
  models_to_run:
    - "xgb"           # XGBoost
    - "lgbm"          # LightGBM
    - "rf"            # Random Forest
    - "ridge"         # Ridge Regression
    - "krr"           # Kernel Ridge Regression
  
  n_trials: 10              # Hyperparameter optimization trials
  quiet_optuna: true        # Suppress detailed output

# --- Feature Engineering ---
features:
  per_smiles_col_generators:
    Catalyst: 
      - type: "morgan"
        radius: 2
        nBits: 1024
    Reactant1: 
      - type: "morgan"
        radius: 2
        nBits: 1024
    Reactant2: 
      - type: "morgan"
        radius: 2
        nBits: 1024
  
  scaling: true

# --- Data Splitting Strategy ---
split_mode: "train_test_split"
split_config:
  train_test_split:
    test_size: 0.2
    random_state: 42
    shuffle: true

# --- Evaluation Metrics ---
evaluation:
  primary_metric: "r2"
  additional_metrics:
    - "rmse"
    - "mae"

# --- Output Settings ---
output:
  save_predictions: true
  save_feature_importance: true
  save_hyperparameters: true

# --- Computational Settings ---
computational:
  n_jobs: -1
  random_state: 42 