evaluation:
  auto_evaluate: true
  compare_with_base: true
  use_test_set: true
save:
  results_dir: output/stacking_results
  save_config_copy: true
  save_evaluation: true
  save_path: output/stacked_models/example_ensemble.pkl
  save_stacker: true
stacking:
  experiment_dir: output/my_experiment
  meta_model:
    auto_train: false
    validation:
      auto_load: true
      size: 100
  method: weighted_average
  models:
  - enabled: true
    name: xgb
    weight: 0.4
  - enabled: true
    name: lgbm
    weight: 0.3
  - enabled: true
    name: catboost
    weight: 0.3
